[package]
name = "matching-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
chrono = "0.4.43"
clap = { version = "4.5.58", features = ["derive"] }
rand = "0.10.0"
rtrb = "0.3.2"
rustc-hash = "2.1.1"
slab = "0.4.12"
